version: "3.2"

services:
    postgres:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            node_net:
                ipv4_address: 172.28.1.5

networks:
    node_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16

volumes:
    postgres_data:
        name: postgres_data_volume
